name: Check Author

on:
  pull_request:
    branches:
      - main
    paths:
      - update-infra-deployments-task-scripts-image/Dockerfile

jobs:
  check-author:
    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v2

      - name: Check the author
        shell: bash
        run: |
          owners=$(yq e ".allowed_users.[]" OWNERS)

          function exists_in_user_list() {
            LIST=$1
            DELIMITER=$2
            VALUE=$3
            LIST_WHITESPACES=`echo $LIST | tr "$DELIMITER" " "`
            for x in $LIST_WHITESPACES; do
                if [ "$x" = "$VALUE" ]; then
                    return 0
                fi
            done
            return 1
          }

          if exists_in_user_list "$owners" " " ${{ github.actor }} ; then
              echo "PR author is in the allowed users list"
              exit 0
          else
              echo "PR author is NOT in the allowed users list"
              exit 1
          fi
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40

      - name: Check if OWNERS file changed
        shell: bash
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [ $file = "OWNERS" ]; then
              echo "OWNERS file is changed"
              exit 1
            else
              echo "OWNERS file is NOT changed"
            fi
          done



